name: Ruff Autofix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para permitir que a Action faça o commit
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Rodar Ruff (Lint + Formatação)
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --fix" # 'check --fix' corrige erros de lógica/estilo
          
      - name: Rodar Ruff Format
        run: ruff format . # Aplica a formatação de código (estilo Black)

      - name: Commit das correções
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: ruff auto-fix e formatação"
