            - name: Prettier Fix
  # You may pin to the exact commit or the version.
  # uses: WorkOfStan/prettier-fix@f2241b3505f4ddb282079e5d381082b71adde392
  uses: WorkOfStan/prettier-fix@v1.1.6.2
  with:
    # If true, commit changes to the current branch
    commit-changes: # optional
    # Commit message for the changes
    commit-message: # optional, default is chore(prettier): apply Prettier fixes automatically
    # Enable extra debug output
    debug: # optional
    # Node.js version to use
    node-version: # optional, default is 20
    # Optional path to a custom Prettier config file
    prettier-config-path: # optional, default is 
    # If true, skip npm initialization and installation
    skip-package-setup: # optional
          
